name: Action Practice

on:
  push:
  schedule:
    - cron: '0 1 * * *'

env:
  TZ: Asia/Shanghai

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Set up environment
        run: pip install requests
      - name: Run
        run: python script.py
